// Code generated by goctl. DO NOT EDIT.
package types

type AddLandOwnerReq struct {
	LandOwnerAddress string `json:"landOwnerAddress"`
}

type AddLandOwnerResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddNotaryReq struct {
	NotaryAddress string `json:"notaryAddress"`
}

type AddNotaryResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddSurveyorReq struct {
	SurveyorAddress string `json:"surveyorAddress"`
}

type AddSurveyorResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GenerateProofOfOwnershipReq struct {
	Owner  string `json:"owner"`
	LandId uint64 `json:"landId"`
}

type GenerateProofOfOwnershipResp struct {
	Code  int    `json:"code"`
	Proof string `json:"proof"`
	Msg   string `json:"msg"`
}

type GetTransactionHistoryReq struct {
	LandId uint64 `json:"landId"`
}

type GetTransactionHistoryResp struct {
	Code int       `json:"code"`
	Data []History `json:"Data"`
	Msg  string    `json:"msg"`
}

type History struct {
	Seller string `json:"seller"`
	Buyer  string `json:"buyer"`
}

type RegisterLandData struct {
	LandId uint64 `json:"landId"`
}

type RegisterLandReq struct {
	Registrant  string  `json:"registrant"`
	Location    string  `json:"location"`
	Area        float32 `json:"area"`
	DetailsHash string  `json:"detailsHash"`
}

type RegisterLandResp struct {
	Code int              `json:"code"`
	Data RegisterLandData `json:"data"`
	Msg  string           `json:"msg"`
}

type TransferOwnershipReq struct {
	LandId   uint64 `json:"landId"`
	NewOwner string `json:newOwner`
}

type TransferOwnershipResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type VerifyData struct {
	IsTampered bool `json:"isTampered"`
}

type VerifyFileHashReq struct {
	LandId   uint64 `json:"landId"`
	FileHash string `json:"fileHash"`
	FileType string `json:"fileType"`
}

type VerifyFileHashResp struct {
	Code int        `json:"code"`
	Data VerifyData `json:"Data"`
	Msg  string     `json:"msg"`
}

type VerifyOwnershipData struct {
	IsOwner bool `json:"isOwner"`
}

type VerifyProofOfOwnershipReq struct {
	LandId uint64 `json:"landId"`
	Proof  string `json:"proof"`
}

type VerifyProofOfOwnershipResp struct {
	Code int                 `json:"code"`
	Data VerifyOwnershipData `json:"Data"`
	Msg  string              `json:"msg"`
}
