// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	land "github.com/cedarHH/LandTradingContract/api/internal/handler/land"
	"github.com/cedarHH/LandTradingContract/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				//
				Method:  http.MethodPost,
				Path:    "/addLandOwner",
				Handler: land.AddLandOwnerHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/addNotary",
				Handler: land.AddNotaryHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/addSurveyor",
				Handler: land.AddSurveyorHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/generateProofOfOwnership",
				Handler: land.GenerateProofOfOwnershipHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/getTransactionHistory",
				Handler: land.GetTransactionHistoryHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/registerLand",
				Handler: land.RegisterLandHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/transferOwnership",
				Handler: land.TransferOwnershipHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/verifyFileHash",
				Handler: land.VerifyFileHashHandler(serverCtx),
			},
			{
				//
				Method:  http.MethodPost,
				Path:    "/verifyProofOfOwnership",
				Handler: land.VerifyProofOfOwnershipHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/land"),
	)
}
